### ISSUE TITLE
Module not found error 

### ISSUE THREAD

**Issue by RealGoose** [oppsec/Pinkerton#2]
doing everything per instructions results in:

Traceback (most recent call last):
  File "/home/USER/Desktop/tools/pinkerton/src/pinkerton/main.py", line 7, in <module>
    from src.pinkerton.settings import props
ModuleNotFoundError: No module named 'src.pinkerton'

**Comment by testaccount245847** [comment]
you have to install that module on your machine. You can install it by pip :)

**Comment by Lulztigre** [comment]
try pip install src==0.0.6

but this might not fix it though

**Comment by 0xdsm** [comment]
> doing everything per instructions results in:
> 
> Traceback (most recent call last): File "/home/USER/Desktop/tools/pinkerton/src/pinkerton/main.py", line 7, in from src.pinkerton.settings import props ModuleNotFoundError: No module named 'src.pinkerton'

Hi @RealGoose, can you inform me what's your OS and current environment configuration? And how are you executing the script?

Best regards,
oppsec.

**Comment by RealGoose** [comment]
I'm on kali and tried executing both main.py in the pinkerton folder and main.py in pinkerton/src/pinkerton.

When I run the first one it throws this error:

Traceback (most recent call last):
  File "/home/USER/Desktop/tools/pinkerton/main.py", line 1, in <module>
    from src.interface.ui import banner
ModuleNotFoundError: No module named 'src.interface'

when I run the second main.py it gives me:

Traceback (most recent call last):
  File "/home/USER/Desktop/tools/pinkerton/src/pinkerton/main.py", line 7, in <module>
    from src.pinkerton.settings import props
ModuleNotFoundError: No module named 'src.pinkerton'


I tried running "pip install src==0.0.6" and "pip3 install src==0.0.6" and both returned:
 
 ERROR: Failed building wheel for src
  Running setup.py clean for src
Failed to build src
Installing collected packages: src
  Running setup.py install for src ... done
Successfully installed src

thank you for your help.

**Comment by xcarx** [comment]
i think you can try to add a point befor src
exemple: import .src.pinkerton

**Comment by 0xdsm** [comment]
> I'm on kali and tried executing both main.py in the pinkerton folder and main.py in pinkerton/src/pinkerton.
> 
> 
> 
> When I run the first one it throws this error:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/home/USER/Desktop/tools/pinkerton/main.py", line 1, in <module>
> 
>     from src.interface.ui import banner
> 
> ModuleNotFoundError: No module named 'src.interface'
> 
> 
> 
> when I run the second main.py it gives me:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/home/USER/Desktop/tools/pinkerton/src/pinkerton/main.py", line 7, in <module>
> 
>     from src.pinkerton.settings import props
> 
> ModuleNotFoundError: No module named 'src.pinkerton'
> 
> 
> 
> 
> 
> I tried running "pip install src==0.0.6" and "pip3 install src==0.0.6" and both returned:
> 
>  
> 
>  ERROR: Failed building wheel for src
> 
>   Running setup.py clean for src
> 
> Failed to build src
> 
> Installing collected packages: src
> 
>   Running setup.py install for src ... done
> 
> Successfully installed src
> 
> 
> 
> thank you for your help.

Hi! I think I already know how to solve this problem, tomorrow I will commit the fix and quote you here again

Best regards,
oppsec

**Comment by RealGoose** [comment]
thank you so much

**Comment by 0xdsm** [comment]
Good morning, @RealGoose!

Can you git pull on your Pinkerton repository or just git clone again? I've pushed the fix and want to know if the problem got solved.

Best regards,
oppsec.

**Comment by RealGoose** [comment]
Thank a lot, the program runs fine now. I appreciate the quick response!
