### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by mrnoob790** [oppsec/Pinkerton#5]
facing these error even after install all requirements 

Traceback (most recent call last):
  File "/home/mmmm/pinkerton/main.py", line 14, in <module>
    perform_checks(args)
  File "/home/mmmm/pinkerton/src/pinkerton/main.py", line 27, in perform_checks
    extract_js(url, page_content)
  File "/home/mmmm/pinkerton/src/pinkerton/main.py", line 57, in extract_js
    direct_scan(jsfile)
  File "/home/mmmm/pinkerton/src/pinkerton/modules/secret.py", line 99, in direct_scan
    match = findall(pattern, content)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 216, in findall
    return _compile(pattern, flags).findall(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 863, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 13

**Comment by rootfebri** [comment]
secret module aren't final
I don't know if they were still up for the project
checkout last update on secret module

**Comment by 0xdsm** [comment]
Apparently, the problem occurs in "match = findall(pattern, content)", as you can see, the code tries to use the _compile function from regex to search for the content on the JavaScript code, I need to investigate if is a problem with the Python 3.11. Can you please send me information about your current environment?

- Python version
- Your OS
- The command you executed

Best regards, oppsec.

**Comment by caocao33** [comment]
> Apparently, the problem occurs in "match = findall(pattern, content)", as you can see, the code tries to use the _compile function from regex to search for the content on the JavaScript code, I need to investigate if is a problem with the Python 3.11. Can you please send me information about your current environment?
> 
> * Python version
> * Your OS
> * The command you executed
> 
> Best regards, oppsec.

**Comment by caocao33** [comment]
> Apparently, the problem occurs in "match = findall(pattern, content)", as you can see, the code tries to use the _compile function from regex to search for the content on the JavaScript code, I need to investigate if is a problem with the Python 3.11. Can you please send me information about your current environment?
> 
> * Python version
> * Your OS
> * The command you executed
> 
> Best regards, oppsec.

same output with me:
Python version: **3.11**
OS: **macOS Sonoma**
My command: `python3 main.py -u http://<target>/`

**Comment by HackerBihari** [comment]
same error

**Comment by 0xdsm** [comment]
Hi guys, that appears to be a problem with the Python 3.11 version, I recommend your guys install Python 3.10 to use this tool. For example, on Linux with Debian-based distros, you can do:

```
sudo apt install python3.10 # Install python3.10
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 110 # Add python 3.10 to alternative options
sudo update-alternatives --config python3 # Open a prompt to select what Python version to use
```

On MacOS:
```
brew install python@3.10
```

Best regards,
oppsec.
