### ISSUE TITLE
Make pinkerton work for python 3.11 and 3.12

### ISSUE THREAD

**Issue by noraj** [oppsec/Pinkerton#7]
Currently, Pinkerton works only for python 3.10 and older, not working on 3.11 and 3.12.

The issue was already reported in https://github.com/oppsec/Pinkerton/issues/5, sticking to python 3.10 is not a viable option

Example:

```
$ pinkerton -u https://pwn.by/noraj/
...

[+] Connected sucessfully with https://pwn.by/noraj/
[*] Extracting JavaScript files from https://pwn.by/noraj/
[+] Found 5 JavaScript file(s) 
[+] Scanning: https://pwn.by/noraj/javascripts/tabs.js
Traceback (most recent call last):
  File "/usr/share/pinkerton/main.py", line 14, in <module>
    perform_checks(args)
  File "/usr/share/pinkerton/src/pinkerton/main.py", line 27, in perform_checks
    extract_js(url, page_content)
  File "/usr/share/pinkerton/src/pinkerton/main.py", line 60, in extract_js
    passed_scan(final_url)
  File "/usr/share/pinkerton/src/pinkerton/modules/secret.py", line 113, in passed_scan
    match = findall(pattern, content)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 216, in findall
    return _compile(pattern, flags).findall(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 982, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 457, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 865, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 457, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 843, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 13
```

If you read chagelog for python 3.11 (https://docs.python.org/3/whatsnew/3.11.html) you can read:

> In [re](https://docs.python.org/3/library/re.html#module-re) [Regular Expression Syntax](https://docs.python.org/3/library/re.html#re-syntax), global inline flags (e.g. (?i)) can now only be used at the start of regular expressions. Using them elsewhere has been deprecated since Python 3.6. (Contributed by Serhiy Storchaka in [bpo-47066](https://bugs.python.org/issue?@action=redirect&bpo=47066).)

Using `(?i)` somewhere else the beginning of the string seems to be causing the issue, I'm surprised you didn't see any warning since it's deprecated since Python 3.6.

All those regexp have `(?i)` outside the start.

https://github.com/oppsec/Pinkerton/blob/da2099c32c58196e5a6c76a6e6d1f91b593b10c5/src/pinkerton/modules/secret.py#L74-L79

**Comment by 0xdsm** [comment]
Hi, @noraj!

First of all, thanks for the contribution!

In my old environment, I've always used python 3.10 or lower, then I didn't experience any problems with Pinkerton, but now I'm using python 3.11+ and the problem occurs with me too. 

Checking your PR and the Python documentation I can see that's a definitive solution to the problem. As you said, if `(?i)` it's not at the start of the regex it's gonna broken. I made the changes that you suggested on my venv environment and apparently, everything works fine now. I'll accept your pull request and, thanks again!

Best regards,
oppsec.
